import type { NextPage } from "next";
import Head from "next/head";
import Header from "./components/Header/Header";
import styles from "../styles/index.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Actum Digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
      </main>
    </>
  );
};

export default Home;
